apiVersion: v1
kind: Pod
metadata:
  name: oomkill-demo
  namespace: demo-pods
spec:
  containers:
    - name: memory-hog
      image: polinux/stress
      resources:
        limits:
          memory: "100Mi"
      command:
        - stress
      args:
        - --vm
        - "1"
        - --vm-bytes
        - "200M"
        - --vm-hang
        - "1"